start_charge_session:
  name: Start a charge session
  description: Starts a charging session with a given card.
  fields:
    device:
      name: Charger
      description: Select the charger to start a session on.
      required: True
      selector:
        device:
          integration: fiftyfive
    card:
      name: Card ID
      description: Identifier of the charge card
      required: True
      selector:
        text:
stop_charge_session:
  name: Stop a charge session
  description: Stops the charging session on the device.
  fields:
    device:
      name: Charger
      description: Select the charger to stop a session on.
      required: True
      selector:
        device:
          integration: fiftyfive