start_charge_session:
  name: Start a charge session
  description: Starts a charging session with a given card.
  fields:
    device:
      name: Charger
      description: Select the charger to start a session on.
      required: True
      selector:
        device:
          integration: fiftyfive
    card:
      name: Card ID
      description: Identifier of the charge card
      required: True
      selector:
        text:
stop_charge_session:
  name: Stop a charge session
  description: Stops the charging session on the device.
  fields:
    device:
      name: Charger
      description: Select the charger to stop a session on.
      required: True
      selector:
        device:
          integration: fiftyfive
soft_reset_charger:
  name: Soft reset a charger
  description: Soft resets a charger.
  fields:
    device:
      name: Charger
      description: Select the charger to soft reset.
      required: True
      selector:
        device:
          integration: fiftyfive
hard_reset_charger:
  name: Hard reset a charger
  description: Hard resets a charger.
  fields:
    device:
      name: Charger
      description: Select the charger to hard reset.
      required: True
      selector:
        device:
          integration: fiftyfive
unlock_connector:
  name: Unlock a connector
  description: Unlock the connector from a charger.
  fields:
    device:
      name: Charger
      description: Select the charger from which to unlock the connector.
      required: True
      selector:
        device:
          integration: fiftyfive
block_charger:
  name: Block a charger
  description: Prevent a charger from being used.
  fields:
    device:
      name: Charger
      description: Select the charger to block.
      required: True
      selector:
        device:
          integration: fiftyfive
unblock_charger:
  name: Unblock a charger
  description: Allow a blocked charger to be used again.
  fields:
    device:
      name: Charger
      description: Select the charger to unblock.
      required: True
      selector:
        device:
          integration: fiftyfive